version: '2'

services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www

  db:
    image: mysql:5.7
    ports:
      - "3388:3306"
    volumes:
      - ./docker-volumes-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: queues_laravel
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    image: redis
    volumes:
      - ./docker-volumes-data/redis:/data

      
